"""update product models

Revision ID: 4008f7416486
Revises: 506e58c288bd
Create Date: 2023-10-03 12:43:07.310757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4008f7416486'
down_revision: Union[str, None] = '506e58c288bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_id', table_name='sales')
    op.drop_index('ix_sales_product_id', table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_products_category', table_name='products')
    op.drop_index('ix_products_id', table_name='products')
    op.drop_index('ix_products_name', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_inventory_id', table_name='inventory')
    op.drop_index('ix_inventory_product_id', table_name='inventory')
    op.drop_table('inventory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_product_id', 'inventory', ['product_id'], unique=False)
    op.create_index('ix_inventory_id', 'inventory', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.create_index('ix_products_category', 'products', ['category'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_product_id', 'sales', ['product_id'], unique=False)
    op.create_index('ix_sales_id', 'sales', ['id'], unique=False)
    # ### end Alembic commands ###
